### ISSUE TITLE
Timeout in network request(Network.java in mitsoko-template )

### ISSUE THREAD

**Issue by ElephantInTheRoomFirst** [fnc12/Viper#9]
Is it possible to do sync call or async call with timeout in request?
protected ResponseTuple doInBackground(String... strings) has
httpConnection.setConnectTimeout(100000);
httpConnection.setReadTimeout(100000);

Created extra issue to track it in better way. 
https://github.com/fnc12/Mitsoko/issues/7

**Comment by fnc12** [comment]
Ok it easy to add this thing. Is it ok that timeout will not be separated to read- and connect- but will be only one common timeout?

**Comment by ElephantInTheRoomFirst** [comment]
I shall prefer separate read and connect as first choice.

**Comment by ElephantInTheRoomFirst** [comment]
Is it still in your ToDo?

**Comment by fnc12** [comment]
Yes, it is. I have much primary work and it takes long time to complete the issue. I'm gonna close it in a week. Thanks for your patience

**Comment by ElephantInTheRoomFirst** [comment]
Did you commit for the issue?

**Comment by fnc12** [comment]
no. But I have it locally. I'm gonna add it today. Sorry for a long time

**Comment by fnc12** [comment]
please check out for the latest commit

**Comment by fnc12** [comment]
Also don't forget to pull mitsoko template repo cause it contains android `Network` class update required to work

**Comment by ElephantInTheRoomFirst** [comment]
Thanks.
